######################################################################
# usual controllers
######################################################################
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

application_comment:
    resource: "@ApplicationCommentBundle/Controller/"
    type:     annotation

# custom rests
comment_thread_api:
    type:     rest
    resource: Application\CommentBundle\Controller\Rest\CommentController
    prefix:   /

app_user_goal_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\UserGoalController
    prefix:   /

app_goal_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\GoalController
    prefix:   /

app_new_feed_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\NewsFeedController
    prefix:   /

app_success_story_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\SuccessStoryController
    prefix:   /

app_main_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\MainRestController
    prefix:   /

app_badge_rest:
    type:     rest
    resource: Application\UserBundle\Controller\Rest\BadgeController
    prefix:   /

app_statistic_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\StatisticController
    prefix:   /

######################################################################
# all imprtant links mut be put abocve this sections for performacen
######################################################################

application_user:
    resource: "@ApplicationUserBundle/Resources/config/routing.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

application_affiliate:
    resource: "@ApplicationAffiliateBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc/

# fos user routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Sonata user routing
sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'

# hwi routes
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

twitter_login:
    path: /login/check-twitter

# PrestaSitemapBundle routing enable
PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /