<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * @param $cachePrefix
     * @return array
     */
    public function getAllCached($cachePrefix)
    {
        $query =
            $this->getEntityManager()
                ->createQueryBuilder()
                ->addSelect('p')
                ->from('AppBundle:Category', 'p')
        ;

        $query->getQuery()->setHint(Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');

        return $query->getQuery()
            ->useResultCache(true, 24 * 3600, 'categories'.$cachePrefix)
            ->getResult();
    }
}
