<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Controller\Rest\StatisticController;
use AppBundle\Traits\StatisticDataFilterTrait;
use Doctrine\ORM\EntityRepository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
    use StatisticDataFilterTrait;

    /**
     * This function is used to get email data for statistic
     *
     * @param $start
     * @param $end
     * @param $groupBy
     * @return array
     */
    public function getEmailStatisticData($groupBy = StatisticController::DAY, $start, $end)
    {
        //set selected date
        $date = 'em.sent';

        //get emails statistic count
        $emails =  $this->getEntityManager()
            ->createQueryBuilder()
            ->select("count(em.id) as send, DATE(".$date.") as created, SUM(CASE WHEN em.seen IS NOT NULL THEN 1 ELSE 0 END) as read")
            ->from('AppBundle:Email', 'em');

        //get filtered statistic data
        $data = $this->filterStatisticData($emails, $date, $groupBy, $start, $end);

        return $data;
    }
}
