<?php

namespace AppBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PlaceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceTypeRepository extends EntityRepository
{
    /**
     * This function is used to get all placeType index by name
     *
     * @return array
     */
    public function findAllIndexByName()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT pt
                           FROM AppBundle:PlaceType pt
                           INDEX BY pt.name
                           ")
            ->getResult();
    }
}
