<?php

namespace Application\AffiliateBundle\Entity\Repository;

/**
 * AffiliateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliateRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $pageLink
     * @param $zone
     * @return array
     */
    public function getAffiliatesByLink($pageLink, $zone)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT a
                           FROM ApplicationAffiliateBundle:Affiliate a
                           JOIN a.affiliateType aType WITH aType.zone = :zone
                           WHERE a.publish = true AND a.links LIKE :pageLink")
            ->setParameter('pageLink', '%' . $pageLink . '%')
            ->setParameter('zone', $zone)
            ->getResult();
    }

    /**
     * @param $link
     * @return mixed
     */
    public function findGoalAffiliateByLink($link)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT a
                           FROM ApplicationAffiliateBundle:Affiliate a
                           WHERE a.links LIKE :link")
            ->setParameter('link', '%' . $link .'%')
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
}
