application_affiliate:
    resource: "@ApplicationAffiliateBundle/Controller/"
    type:     annotation
    prefix:   /

application_afiliate_rest:
    type:     rest
    resource: Application\AffiliateBundle\Controller\Rest\AffiliateController
    prefix:   /